services:
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: ronaldaodb
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
     - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgres/data

volumes:
  pgdata: {}
